# Generated by Django 4.2.9 on 2024-07-06 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('rally', 'Rally'), ('hill_climb', 'Hill Climb'), ('autocross', 'Autocross'), ('karting', 'Karting')], max_length=50)),
                ('provider', models.CharField(choices=[('kronobot', 'Kronobot'), ('kronolive', 'Kronolive'), ('other', 'Other')], max_length=50)),
                ('status', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('provider_inscriptions_url', models.URLField(blank=True, null=True)),
                ('provider_event_url', models.URLField(blank=True, null=True)),
                ('provider_times_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
